---
services:
  - docker

env:
  - distribution: metasploit

before_install:
  - 'sudo docker build --no-cache --rm --file=Dockerfile.${distribution} --tag=diodonfrost/${distribution}:metasploit .'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro diodonfrost/${distribution}:metasploit sleep 300 > "${container_id}"'

  # Test role
  - 'inspec exec tests/inspec -t docker://$(cat ${container_id})'


after_success:
  # Login on dockerhub.io before pushing
  - 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'

  # Pushing image to dockerhub
  - 'docker push diodonfrost/${distribution}:latest'

  # Delete container
  - 'sudo docker rm -f "$(cat ${container_id})"'
